/* soapWEBLOGINSOAP11BindingProxy.cpp
   Generated by gSOAP 2.8.13 from weblogin.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapWEBLOGINSOAP11BindingProxy.h"

WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy()
{	WEBLOGINSOAP11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy(const struct soap &_soap) : soap(_soap)
{ }

WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy(const char *url)
{	WEBLOGINSOAP11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy(soap_mode iomode)
{	WEBLOGINSOAP11BindingProxy_init(iomode, iomode);
}

WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy(const char *url, soap_mode iomode)
{	WEBLOGINSOAP11BindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy(soap_mode imode, soap_mode omode)
{	WEBLOGINSOAP11BindingProxy_init(imode, omode);
}

WEBLOGINSOAP11BindingProxy::~WEBLOGINSOAP11BindingProxy()
{ }

void WEBLOGINSOAP11BindingProxy::WEBLOGINSOAP11BindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://weblogin.wsbeans.iseries", NULL, NULL},
	{"ns2", "http://weblogin.wsbeans.iseries/xsd", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void WEBLOGINSOAP11BindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void WEBLOGINSOAP11BindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	WEBLOGINSOAP11BindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void WEBLOGINSOAP11BindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *WEBLOGINSOAP11BindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *WEBLOGINSOAP11BindingProxy::soap_fault()
{	return this->fault;
}

const char *WEBLOGINSOAP11BindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *WEBLOGINSOAP11BindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int WEBLOGINSOAP11BindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int WEBLOGINSOAP11BindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void WEBLOGINSOAP11BindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void WEBLOGINSOAP11BindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *WEBLOGINSOAP11BindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int WEBLOGINSOAP11BindingProxy::weblogin_USCOREXML(const char *endpoint, const char *soap_action, _ns2__weblogin_USCOREXML *ns2__weblogin_USCOREXML, _ns2__weblogin_USCOREXMLResponse *ns2__weblogin_USCOREXMLResponse)
{	struct soap *soap = this;
	struct __ns1__weblogin_USCOREXML soap_tmp___ns1__weblogin_USCOREXML;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.29.171.251:10000/web/services/WEBLOGIN";
	if (soap_action == NULL)
		soap_action = "urn:weblogin_XML";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__weblogin_USCOREXML.ns2__weblogin_USCOREXML = ns2__weblogin_USCOREXML;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__weblogin_USCOREXML(soap, &soap_tmp___ns1__weblogin_USCOREXML);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__weblogin_USCOREXML(soap, &soap_tmp___ns1__weblogin_USCOREXML, "-ns1:weblogin_XML", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__weblogin_USCOREXML(soap, &soap_tmp___ns1__weblogin_USCOREXML, "-ns1:weblogin_XML", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__weblogin_USCOREXMLResponse)
		return soap_closesock(soap);
	ns2__weblogin_USCOREXMLResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__weblogin_USCOREXMLResponse->soap_get(soap, "ns2:weblogin_XMLResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WEBLOGINSOAP11BindingProxy::weblogin(const char *endpoint, const char *soap_action, _ns2__weblogin *ns2__weblogin, _ns2__webloginResponse *ns2__webloginResponse)
{	struct soap *soap = this;
	struct __ns1__weblogin soap_tmp___ns1__weblogin;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.29.171.251:10000/web/services/WEBLOGIN";
	if (soap_action == NULL)
		soap_action = "urn:weblogin";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__weblogin.ns2__weblogin = ns2__weblogin;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__weblogin(soap, &soap_tmp___ns1__weblogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__weblogin(soap, &soap_tmp___ns1__weblogin, "-ns1:weblogin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__weblogin(soap, &soap_tmp___ns1__weblogin, "-ns1:weblogin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__webloginResponse)
		return soap_closesock(soap);
	ns2__webloginResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__webloginResponse->soap_get(soap, "ns2:webloginResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
