/* soapH.h
   Generated by gSOAP 2.8.13 from weblogin.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin(soap), soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin(soap), soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin(soap), soap_serialize_std__string(soap, data), soap_begin_send(soap) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__weblogin_USCOREXMLResponse
#define SOAP_TYPE__ns2__weblogin_USCOREXMLResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__weblogin_USCOREXMLResponse(struct soap*, const char*, int, const _ns2__weblogin_USCOREXMLResponse *, const char*);
SOAP_FMAC3 _ns2__weblogin_USCOREXMLResponse * SOAP_FMAC4 soap_in__ns2__weblogin_USCOREXMLResponse(struct soap*, const char*, _ns2__weblogin_USCOREXMLResponse *, const char*);

#ifndef soap_write__ns2__weblogin_USCOREXMLResponse
#define soap_write__ns2__weblogin_USCOREXMLResponse(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns2:weblogin_XMLResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__weblogin_USCOREXMLResponse * SOAP_FMAC4 soap_get__ns2__weblogin_USCOREXMLResponse(struct soap*, _ns2__weblogin_USCOREXMLResponse *, const char*, const char*);

#ifndef soap_read__ns2__weblogin_USCOREXMLResponse
#define soap_read__ns2__weblogin_USCOREXMLResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__weblogin_USCOREXMLResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns2__weblogin_USCOREXMLResponse * SOAP_FMAC2 soap_instantiate__ns2__weblogin_USCOREXMLResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns2__weblogin_USCOREXMLResponse * soap_new__ns2__weblogin_USCOREXMLResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns2__weblogin_USCOREXMLResponse(soap, n, NULL, NULL, NULL); }

inline _ns2__weblogin_USCOREXMLResponse * soap_new_req__ns2__weblogin_USCOREXMLResponse(struct soap *soap) { _ns2__weblogin_USCOREXMLResponse *_p = soap_instantiate__ns2__weblogin_USCOREXMLResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns2__weblogin_USCOREXMLResponse * soap_new_set__ns2__weblogin_USCOREXMLResponse(struct soap *soap, std::string *return_) { _ns2__weblogin_USCOREXMLResponse *_p = soap_instantiate__ns2__weblogin_USCOREXMLResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns2__weblogin_USCOREXMLResponse::return_ = return_; } return _p; }

inline void soap_delete__ns2__weblogin_USCOREXMLResponse(struct soap *soap, _ns2__weblogin_USCOREXMLResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__weblogin_USCOREXMLResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__weblogin_USCOREXML
#define SOAP_TYPE__ns2__weblogin_USCOREXML (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__weblogin_USCOREXML(struct soap*, const char*, int, const _ns2__weblogin_USCOREXML *, const char*);
SOAP_FMAC3 _ns2__weblogin_USCOREXML * SOAP_FMAC4 soap_in__ns2__weblogin_USCOREXML(struct soap*, const char*, _ns2__weblogin_USCOREXML *, const char*);

#ifndef soap_write__ns2__weblogin_USCOREXML
#define soap_write__ns2__weblogin_USCOREXML(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns2:weblogin_XML", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__weblogin_USCOREXML * SOAP_FMAC4 soap_get__ns2__weblogin_USCOREXML(struct soap*, _ns2__weblogin_USCOREXML *, const char*, const char*);

#ifndef soap_read__ns2__weblogin_USCOREXML
#define soap_read__ns2__weblogin_USCOREXML(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__weblogin_USCOREXML(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns2__weblogin_USCOREXML * SOAP_FMAC2 soap_instantiate__ns2__weblogin_USCOREXML(struct soap*, int, const char*, const char*, size_t*);

inline _ns2__weblogin_USCOREXML * soap_new__ns2__weblogin_USCOREXML(struct soap *soap, int n = -1) { return soap_instantiate__ns2__weblogin_USCOREXML(soap, n, NULL, NULL, NULL); }

inline _ns2__weblogin_USCOREXML * soap_new_req__ns2__weblogin_USCOREXML(struct soap *soap) { _ns2__weblogin_USCOREXML *_p = soap_instantiate__ns2__weblogin_USCOREXML(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns2__weblogin_USCOREXML * soap_new_set__ns2__weblogin_USCOREXML(struct soap *soap, ns2__WEBLOGINInput *param0) { _ns2__weblogin_USCOREXML *_p = soap_instantiate__ns2__weblogin_USCOREXML(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns2__weblogin_USCOREXML::param0 = param0; } return _p; }

inline void soap_delete__ns2__weblogin_USCOREXML(struct soap *soap, _ns2__weblogin_USCOREXML *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__weblogin_USCOREXML(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__webloginResponse
#define SOAP_TYPE__ns2__webloginResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__webloginResponse(struct soap*, const char*, int, const _ns2__webloginResponse *, const char*);
SOAP_FMAC3 _ns2__webloginResponse * SOAP_FMAC4 soap_in__ns2__webloginResponse(struct soap*, const char*, _ns2__webloginResponse *, const char*);

#ifndef soap_write__ns2__webloginResponse
#define soap_write__ns2__webloginResponse(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns2:webloginResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__webloginResponse * SOAP_FMAC4 soap_get__ns2__webloginResponse(struct soap*, _ns2__webloginResponse *, const char*, const char*);

#ifndef soap_read__ns2__webloginResponse
#define soap_read__ns2__webloginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__webloginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns2__webloginResponse * SOAP_FMAC2 soap_instantiate__ns2__webloginResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns2__webloginResponse * soap_new__ns2__webloginResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns2__webloginResponse(soap, n, NULL, NULL, NULL); }

inline _ns2__webloginResponse * soap_new_req__ns2__webloginResponse(struct soap *soap) { _ns2__webloginResponse *_p = soap_instantiate__ns2__webloginResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns2__webloginResponse * soap_new_set__ns2__webloginResponse(struct soap *soap, ns2__WEBLOGINResult *return_) { _ns2__webloginResponse *_p = soap_instantiate__ns2__webloginResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns2__webloginResponse::return_ = return_; } return _p; }

inline void soap_delete__ns2__webloginResponse(struct soap *soap, _ns2__webloginResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__webloginResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__weblogin
#define SOAP_TYPE__ns2__weblogin (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__weblogin(struct soap*, const char*, int, const _ns2__weblogin *, const char*);
SOAP_FMAC3 _ns2__weblogin * SOAP_FMAC4 soap_in__ns2__weblogin(struct soap*, const char*, _ns2__weblogin *, const char*);

#ifndef soap_write__ns2__weblogin
#define soap_write__ns2__weblogin(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns2:weblogin", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__weblogin * SOAP_FMAC4 soap_get__ns2__weblogin(struct soap*, _ns2__weblogin *, const char*, const char*);

#ifndef soap_read__ns2__weblogin
#define soap_read__ns2__weblogin(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__weblogin(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 _ns2__weblogin * SOAP_FMAC2 soap_instantiate__ns2__weblogin(struct soap*, int, const char*, const char*, size_t*);

inline _ns2__weblogin * soap_new__ns2__weblogin(struct soap *soap, int n = -1) { return soap_instantiate__ns2__weblogin(soap, n, NULL, NULL, NULL); }

inline _ns2__weblogin * soap_new_req__ns2__weblogin(struct soap *soap) { _ns2__weblogin *_p = soap_instantiate__ns2__weblogin(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns2__weblogin * soap_new_set__ns2__weblogin(struct soap *soap, ns2__WEBLOGINInput *param0) { _ns2__weblogin *_p = soap_instantiate__ns2__weblogin(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns2__weblogin::param0 = param0; } return _p; }

inline void soap_delete__ns2__weblogin(struct soap *soap, _ns2__weblogin *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__weblogin(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__WEBLOGINResult
#define SOAP_TYPE_ns2__WEBLOGINResult (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WEBLOGINResult(struct soap*, const char*, int, const ns2__WEBLOGINResult *, const char*);
SOAP_FMAC3 ns2__WEBLOGINResult * SOAP_FMAC4 soap_in_ns2__WEBLOGINResult(struct soap*, const char*, ns2__WEBLOGINResult *, const char*);

#ifndef soap_write_ns2__WEBLOGINResult
#define soap_write_ns2__WEBLOGINResult(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns2:WEBLOGINResult", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns2__WEBLOGINResult * SOAP_FMAC4 soap_get_ns2__WEBLOGINResult(struct soap*, ns2__WEBLOGINResult *, const char*, const char*);

#ifndef soap_read_ns2__WEBLOGINResult
#define soap_read_ns2__WEBLOGINResult(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__WEBLOGINResult(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns2__WEBLOGINResult * SOAP_FMAC2 soap_instantiate_ns2__WEBLOGINResult(struct soap*, int, const char*, const char*, size_t*);

inline ns2__WEBLOGINResult * soap_new_ns2__WEBLOGINResult(struct soap *soap, int n = -1) { return soap_instantiate_ns2__WEBLOGINResult(soap, n, NULL, NULL, NULL); }

inline ns2__WEBLOGINResult * soap_new_req_ns2__WEBLOGINResult(struct soap *soap) { ns2__WEBLOGINResult *_p = soap_instantiate_ns2__WEBLOGINResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns2__WEBLOGINResult * soap_new_set_ns2__WEBLOGINResult(struct soap *soap, std::string *_USCOREERRORCODE, std::string *_USCOREMESSAGE) { ns2__WEBLOGINResult *_p = soap_instantiate_ns2__WEBLOGINResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns2__WEBLOGINResult::_USCOREERRORCODE = _USCOREERRORCODE; _p->ns2__WEBLOGINResult::_USCOREMESSAGE = _USCOREMESSAGE; } return _p; }

inline void soap_delete_ns2__WEBLOGINResult(struct soap *soap, ns2__WEBLOGINResult *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__WEBLOGINResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__WEBLOGINInput
#define SOAP_TYPE_ns2__WEBLOGINInput (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__WEBLOGINInput(struct soap*, const char*, int, const ns2__WEBLOGINInput *, const char*);
SOAP_FMAC3 ns2__WEBLOGINInput * SOAP_FMAC4 soap_in_ns2__WEBLOGINInput(struct soap*, const char*, ns2__WEBLOGINInput *, const char*);

#ifndef soap_write_ns2__WEBLOGINInput
#define soap_write_ns2__WEBLOGINInput(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns2:WEBLOGINInput", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns2__WEBLOGINInput * SOAP_FMAC4 soap_get_ns2__WEBLOGINInput(struct soap*, ns2__WEBLOGINInput *, const char*, const char*);

#ifndef soap_read_ns2__WEBLOGINInput
#define soap_read_ns2__WEBLOGINInput(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__WEBLOGINInput(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns2__WEBLOGINInput * SOAP_FMAC2 soap_instantiate_ns2__WEBLOGINInput(struct soap*, int, const char*, const char*, size_t*);

inline ns2__WEBLOGINInput * soap_new_ns2__WEBLOGINInput(struct soap *soap, int n = -1) { return soap_instantiate_ns2__WEBLOGINInput(soap, n, NULL, NULL, NULL); }

inline ns2__WEBLOGINInput * soap_new_req_ns2__WEBLOGINInput(struct soap *soap) { ns2__WEBLOGINInput *_p = soap_instantiate_ns2__WEBLOGINInput(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns2__WEBLOGINInput * soap_new_set_ns2__WEBLOGINInput(struct soap *soap, std::string *_USCOREERRORCODE, std::string *_USCOREMESSAGE, std::string *_USCOREPASSWORD, std::string *_USCOREUSERID) { ns2__WEBLOGINInput *_p = soap_instantiate_ns2__WEBLOGINInput(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns2__WEBLOGINInput::_USCOREERRORCODE = _USCOREERRORCODE; _p->ns2__WEBLOGINInput::_USCOREMESSAGE = _USCOREMESSAGE; _p->ns2__WEBLOGINInput::_USCOREPASSWORD = _USCOREPASSWORD; _p->ns2__WEBLOGINInput::_USCOREUSERID = _USCOREUSERID; } return _p; }

inline void soap_delete_ns2__WEBLOGINInput(struct soap *soap, ns2__WEBLOGINInput *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__WEBLOGINInput(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__weblogin
#define SOAP_TYPE___ns1__weblogin (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__weblogin(struct soap*, struct __ns1__weblogin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__weblogin(struct soap*, const struct __ns1__weblogin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__weblogin(struct soap*, const char*, int, const struct __ns1__weblogin *, const char*);
SOAP_FMAC3 struct __ns1__weblogin * SOAP_FMAC4 soap_in___ns1__weblogin(struct soap*, const char*, struct __ns1__weblogin *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__weblogin(struct soap*, const struct __ns1__weblogin *, const char*, const char*);

#ifndef soap_write___ns1__weblogin
#define soap_write___ns1__weblogin(soap, data) ( soap_begin(soap), soap_serialize___ns1__weblogin(soap, data), soap_begin_send(soap) || soap_put___ns1__weblogin(soap, data, "-ns1:weblogin", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__weblogin * SOAP_FMAC4 soap_get___ns1__weblogin(struct soap*, struct __ns1__weblogin *, const char*, const char*);

#ifndef soap_read___ns1__weblogin
#define soap_read___ns1__weblogin(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__weblogin(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__weblogin * SOAP_FMAC2 soap_instantiate___ns1__weblogin(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__weblogin * soap_new___ns1__weblogin(struct soap *soap, int n = -1) { return soap_instantiate___ns1__weblogin(soap, n, NULL, NULL, NULL); }

inline struct __ns1__weblogin * soap_new_req___ns1__weblogin(struct soap *soap) { struct __ns1__weblogin *_p = soap_instantiate___ns1__weblogin(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__weblogin(soap, _p); } return _p; }

inline struct __ns1__weblogin * soap_new_set___ns1__weblogin(struct soap *soap, _ns2__weblogin *ns2__weblogin) { struct __ns1__weblogin *_p = soap_instantiate___ns1__weblogin(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__weblogin(soap, _p); _p->ns2__weblogin = ns2__weblogin; } return _p; }

inline void soap_delete___ns1__weblogin(struct soap *soap, struct __ns1__weblogin *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__weblogin(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__weblogin_USCOREXML
#define SOAP_TYPE___ns1__weblogin_USCOREXML (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__weblogin_USCOREXML(struct soap*, struct __ns1__weblogin_USCOREXML *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__weblogin_USCOREXML(struct soap*, const struct __ns1__weblogin_USCOREXML *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__weblogin_USCOREXML(struct soap*, const char*, int, const struct __ns1__weblogin_USCOREXML *, const char*);
SOAP_FMAC3 struct __ns1__weblogin_USCOREXML * SOAP_FMAC4 soap_in___ns1__weblogin_USCOREXML(struct soap*, const char*, struct __ns1__weblogin_USCOREXML *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__weblogin_USCOREXML(struct soap*, const struct __ns1__weblogin_USCOREXML *, const char*, const char*);

#ifndef soap_write___ns1__weblogin_USCOREXML
#define soap_write___ns1__weblogin_USCOREXML(soap, data) ( soap_begin(soap), soap_serialize___ns1__weblogin_USCOREXML(soap, data), soap_begin_send(soap) || soap_put___ns1__weblogin_USCOREXML(soap, data, "-ns1:weblogin_XML", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__weblogin_USCOREXML * SOAP_FMAC4 soap_get___ns1__weblogin_USCOREXML(struct soap*, struct __ns1__weblogin_USCOREXML *, const char*, const char*);

#ifndef soap_read___ns1__weblogin_USCOREXML
#define soap_read___ns1__weblogin_USCOREXML(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__weblogin_USCOREXML(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__weblogin_USCOREXML * SOAP_FMAC2 soap_instantiate___ns1__weblogin_USCOREXML(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__weblogin_USCOREXML * soap_new___ns1__weblogin_USCOREXML(struct soap *soap, int n = -1) { return soap_instantiate___ns1__weblogin_USCOREXML(soap, n, NULL, NULL, NULL); }

inline struct __ns1__weblogin_USCOREXML * soap_new_req___ns1__weblogin_USCOREXML(struct soap *soap) { struct __ns1__weblogin_USCOREXML *_p = soap_instantiate___ns1__weblogin_USCOREXML(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__weblogin_USCOREXML(soap, _p); } return _p; }

inline struct __ns1__weblogin_USCOREXML * soap_new_set___ns1__weblogin_USCOREXML(struct soap *soap, _ns2__weblogin_USCOREXML *ns2__weblogin_USCOREXML) { struct __ns1__weblogin_USCOREXML *_p = soap_instantiate___ns1__weblogin_USCOREXML(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__weblogin_USCOREXML(soap, _p); _p->ns2__weblogin_USCOREXML = ns2__weblogin_USCOREXML; } return _p; }

inline void soap_delete___ns1__weblogin_USCOREXML(struct soap *soap, struct __ns1__weblogin_USCOREXML *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__weblogin_USCOREXML(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns2__webloginResponse
#define SOAP_TYPE_PointerTo_ns2__webloginResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__webloginResponse(struct soap*, _ns2__webloginResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__webloginResponse(struct soap*, const char *, int, _ns2__webloginResponse *const*, const char *);
SOAP_FMAC3 _ns2__webloginResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__webloginResponse(struct soap*, const char*, _ns2__webloginResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__webloginResponse(struct soap*, _ns2__webloginResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns2__webloginResponse
#define soap_write_PointerTo_ns2__webloginResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns2__webloginResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns2__webloginResponse(soap, data, "ns2:webloginResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__webloginResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__webloginResponse(struct soap*, _ns2__webloginResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__webloginResponse
#define soap_read_PointerTo_ns2__webloginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__webloginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns2__weblogin
#define SOAP_TYPE_PointerTo_ns2__weblogin (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__weblogin(struct soap*, _ns2__weblogin *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__weblogin(struct soap*, const char *, int, _ns2__weblogin *const*, const char *);
SOAP_FMAC3 _ns2__weblogin ** SOAP_FMAC4 soap_in_PointerTo_ns2__weblogin(struct soap*, const char*, _ns2__weblogin **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__weblogin(struct soap*, _ns2__weblogin *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns2__weblogin
#define soap_write_PointerTo_ns2__weblogin(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns2__weblogin(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns2__weblogin(soap, data, "ns2:weblogin", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__weblogin ** SOAP_FMAC4 soap_get_PointerTo_ns2__weblogin(struct soap*, _ns2__weblogin **, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__weblogin
#define soap_read_PointerTo_ns2__weblogin(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__weblogin(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns2__weblogin_USCOREXMLResponse
#define SOAP_TYPE_PointerTo_ns2__weblogin_USCOREXMLResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__weblogin_USCOREXMLResponse(struct soap*, _ns2__weblogin_USCOREXMLResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__weblogin_USCOREXMLResponse(struct soap*, const char *, int, _ns2__weblogin_USCOREXMLResponse *const*, const char *);
SOAP_FMAC3 _ns2__weblogin_USCOREXMLResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__weblogin_USCOREXMLResponse(struct soap*, const char*, _ns2__weblogin_USCOREXMLResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__weblogin_USCOREXMLResponse(struct soap*, _ns2__weblogin_USCOREXMLResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns2__weblogin_USCOREXMLResponse
#define soap_write_PointerTo_ns2__weblogin_USCOREXMLResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns2__weblogin_USCOREXMLResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns2__weblogin_USCOREXMLResponse(soap, data, "ns2:weblogin_XMLResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__weblogin_USCOREXMLResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__weblogin_USCOREXMLResponse(struct soap*, _ns2__weblogin_USCOREXMLResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__weblogin_USCOREXMLResponse
#define soap_read_PointerTo_ns2__weblogin_USCOREXMLResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__weblogin_USCOREXMLResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns2__weblogin_USCOREXML
#define SOAP_TYPE_PointerTo_ns2__weblogin_USCOREXML (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__weblogin_USCOREXML(struct soap*, _ns2__weblogin_USCOREXML *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__weblogin_USCOREXML(struct soap*, const char *, int, _ns2__weblogin_USCOREXML *const*, const char *);
SOAP_FMAC3 _ns2__weblogin_USCOREXML ** SOAP_FMAC4 soap_in_PointerTo_ns2__weblogin_USCOREXML(struct soap*, const char*, _ns2__weblogin_USCOREXML **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__weblogin_USCOREXML(struct soap*, _ns2__weblogin_USCOREXML *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns2__weblogin_USCOREXML
#define soap_write_PointerTo_ns2__weblogin_USCOREXML(soap, data) ( soap_begin(soap), soap_serialize_PointerTo_ns2__weblogin_USCOREXML(soap, data), soap_begin_send(soap) || soap_put_PointerTo_ns2__weblogin_USCOREXML(soap, data, "ns2:weblogin_XML", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 _ns2__weblogin_USCOREXML ** SOAP_FMAC4 soap_get_PointerTo_ns2__weblogin_USCOREXML(struct soap*, _ns2__weblogin_USCOREXML **, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__weblogin_USCOREXML
#define soap_read_PointerTo_ns2__weblogin_USCOREXML(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__weblogin_USCOREXML(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__WEBLOGINResult
#define SOAP_TYPE_PointerTons2__WEBLOGINResult (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__WEBLOGINResult(struct soap*, ns2__WEBLOGINResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__WEBLOGINResult(struct soap*, const char *, int, ns2__WEBLOGINResult *const*, const char *);
SOAP_FMAC3 ns2__WEBLOGINResult ** SOAP_FMAC4 soap_in_PointerTons2__WEBLOGINResult(struct soap*, const char*, ns2__WEBLOGINResult **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__WEBLOGINResult(struct soap*, ns2__WEBLOGINResult *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__WEBLOGINResult
#define soap_write_PointerTons2__WEBLOGINResult(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__WEBLOGINResult(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__WEBLOGINResult(soap, data, "ns2:WEBLOGINResult", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns2__WEBLOGINResult ** SOAP_FMAC4 soap_get_PointerTons2__WEBLOGINResult(struct soap*, ns2__WEBLOGINResult **, const char*, const char*);

#ifndef soap_read_PointerTons2__WEBLOGINResult
#define soap_read_PointerTons2__WEBLOGINResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__WEBLOGINResult(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__WEBLOGINInput
#define SOAP_TYPE_PointerTons2__WEBLOGINInput (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__WEBLOGINInput(struct soap*, ns2__WEBLOGINInput *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__WEBLOGINInput(struct soap*, const char *, int, ns2__WEBLOGINInput *const*, const char *);
SOAP_FMAC3 ns2__WEBLOGINInput ** SOAP_FMAC4 soap_in_PointerTons2__WEBLOGINInput(struct soap*, const char*, ns2__WEBLOGINInput **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__WEBLOGINInput(struct soap*, ns2__WEBLOGINInput *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__WEBLOGINInput
#define soap_write_PointerTons2__WEBLOGINInput(soap, data) ( soap_begin(soap), soap_serialize_PointerTons2__WEBLOGINInput(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__WEBLOGINInput(soap, data, "ns2:WEBLOGINInput", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns2__WEBLOGINInput ** SOAP_FMAC4 soap_get_PointerTons2__WEBLOGINInput(struct soap*, ns2__WEBLOGINInput **, const char*, const char*);

#ifndef soap_read_PointerTons2__WEBLOGINInput
#define soap_read_PointerTons2__WEBLOGINInput(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__WEBLOGINInput(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_begin(soap), soap_serialize_PointerTostd__string(soap, data), soap_begin_send(soap) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin(soap), soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin(soap), soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

/* End of soapH.h */
