/* soapWEBLOGINSOAP11BindingProxy.h
   Generated by gSOAP 2.8.13 from weblogin.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapWEBLOGINSOAP11BindingProxy_H
#define soapWEBLOGINSOAP11BindingProxy_H
#include "soapH.h"

class SOAP_CMAC WEBLOGINSOAP11BindingProxy : public soap
{ public:
	/// Endpoint URL of service 'WEBLOGINSOAP11BindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	WEBLOGINSOAP11BindingProxy();
	/// Construct from another engine state
	WEBLOGINSOAP11BindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	WEBLOGINSOAP11BindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	WEBLOGINSOAP11BindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	WEBLOGINSOAP11BindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	WEBLOGINSOAP11BindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~WEBLOGINSOAP11BindingProxy();
	/// Initializer used by constructors
	virtual	void WEBLOGINSOAP11BindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'weblogin_XML' (returns error code or SOAP_OK)
	virtual	int weblogin_USCOREXML(_ns2__weblogin_USCOREXML *ns2__weblogin_USCOREXML, _ns2__weblogin_USCOREXMLResponse *ns2__weblogin_USCOREXMLResponse) { return this->weblogin_USCOREXML(NULL, NULL, ns2__weblogin_USCOREXML, ns2__weblogin_USCOREXMLResponse); }
	virtual	int weblogin_USCOREXML(const char *endpoint, const char *soap_action, _ns2__weblogin_USCOREXML *ns2__weblogin_USCOREXML, _ns2__weblogin_USCOREXMLResponse *ns2__weblogin_USCOREXMLResponse);

	/// Web service operation 'weblogin' (returns error code or SOAP_OK)
	virtual	int weblogin(_ns2__weblogin *ns2__weblogin, _ns2__webloginResponse *ns2__webloginResponse) { return this->weblogin(NULL, NULL, ns2__weblogin, ns2__webloginResponse); }
	virtual	int weblogin(const char *endpoint, const char *soap_action, _ns2__weblogin *ns2__weblogin, _ns2__webloginResponse *ns2__webloginResponse);
};
#endif
